/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Logo: typeof import('./components/Logo.vue')['default']
    SharedSubtitle: typeof import('./components/SharedSubtitle.vue')['default']
  }
}
